#!/usr/bin/env bash
#
# Durable preview stack for the multi-chain build: backend + dev server, each
# behind a Cloudflare quick tunnel.
#
# Run by systemd (polaris-preview.service) rather than as a background shell job,
# because the agent harness reaps background jobs between turns — the same reason
# the Arc swarm runs as a unit. If any child dies, this script exits and systemd
# restarts the whole stack, which keeps the dev server's VITE_API_URL in step with
# whatever hostname the API tunnel comes back with.
#
# Ports are deliberate: 8787 and 5173 are held by unrelated processes on this box.
set -u

ROOT=/root/polarisonbot
LOG=/var/log/polaris-preview
API_PORT=8791
WEB_PORT=5180
mkdir -p "$LOG"

# Clear the published URLs immediately. Quick tunnels get a NEW hostname on every
# restart, so a stale urls.env would hand out addresses that are already dead
# (Cloudflare error 1033) — the file must be absent while the stack is coming up,
# not merely out of date.
rm -f "$LOG/urls.env"

# Kill the whole process group on exit so a restart never leaves orphaned
# tunnels pointing at a dead upstream (which is what produced 502s before).
cleanup() { kill 0 2>/dev/null; }
trap cleanup EXIT INT TERM

url_from() { grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$1" 2>/dev/null | head -1; }
wait_for_url() {
  local f=$1 u=""
  for _ in $(seq 1 60); do u=$(url_from "$f"); [ -n "$u" ] && { echo "$u"; return 0; }; sleep 2; done
  return 1
}

# ── 1. backend: both networks, hosted personas on ────────────────────────────
cd "$ROOT/server" || exit 1
PORT=$API_PORT SWARM_NETWORKS=arc-testnet,botchain-testnet HOSTED_AGENTS=1 \
  node runtime.js > "$LOG/api.log" 2>&1 &
until curl -sf --max-time 3 "http://localhost:$API_PORT/health" >/dev/null 2>&1; do sleep 2; done
echo "[preview] backend up on :$API_PORT"

# ── 2. tunnel the backend ────────────────────────────────────────────────────
: > "$LOG/tunnel-api.log"
cloudflared tunnel --url "http://localhost:$API_PORT" --no-autoupdate > "$LOG/tunnel-api.log" 2>&1 &
API_URL=$(wait_for_url "$LOG/tunnel-api.log") || { echo "[preview] API tunnel never produced a URL"; exit 1; }
echo "[preview] API tunnel: $API_URL"

# ── 3. point the dev server at that tunnel, then start it ────────────────────
# Vite reads VITE_API_URL at boot, so this must be written before it starts.
cd "$ROOT" || exit 1
REOWN=$(grep -oP '^VITE_WALLETCONNECT_PROJECT_ID=\K\S+' .env 2>/dev/null)
{
  echo "# Generated by scripts/preview.sh — do not edit by hand."
  echo "VITE_API_URL=$API_URL"
  echo "VITE_REOWN_PROJECT_ID=$REOWN"
} > .env.development.local
npm run dev -- --port "$WEB_PORT" --host > "$LOG/web.log" 2>&1 &
until curl -sf --max-time 3 -o /dev/null "http://localhost:$WEB_PORT/" 2>/dev/null; do sleep 2; done
echo "[preview] dev server up on :$WEB_PORT"

# ── 4. tunnel the dev server ─────────────────────────────────────────────────
: > "$LOG/tunnel-web.log"
cloudflared tunnel --url "http://localhost:$WEB_PORT" --no-autoupdate > "$LOG/tunnel-web.log" 2>&1 &
APP_URL=$(wait_for_url "$LOG/tunnel-web.log") || { echo "[preview] web tunnel never produced a URL"; exit 1; }

# Current URLs, so they can always be read back without grepping logs.
{ echo "APP=$APP_URL"; echo "API=$API_URL"; } > "$LOG/urls.env"
echo "[preview] APP $APP_URL"
echo "[preview] API $API_URL"

# Exit as soon as any child dies → systemd restarts the stack as a unit.
wait -n
echo "[preview] a child exited — restarting stack"
